"""Count cleaned feature+label fingerprints shared by CICIDS source CSVs.

The cleaner concatenates its eight frames in CIC_FILES order. Its report
provides exact segment lengths, allowing bounded-memory parquet batch reads
without adding a source-file column to the established task protocol.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.data.clean import CIC_FILES


def audit(parquet_path: Path, report_path: Path) -> tuple[list[dict], list[tuple[str, str, int]]]:
    report = pd.read_csv(report_path)
    names = list(CIC_FILES)
    if report["day"].tolist() != [
        "monday", "tuesday", "wednesday", "thursday", "thursday",
        "friday", "friday", "friday",
    ] or len(report) != len(names):
        raise ValueError("cleaning report no longer matches CIC_FILES concatenation order")
    sizes = report["rows_out"].to_numpy(dtype=np.int64)
    ends = np.cumsum(sizes)
    pf = pq.ParquetFile(parquet_path)
    if int(ends[-1]) != pf.metadata.num_rows:
        raise ValueError("cleaning report row count differs from cleaned parquet")
    columns = [c for c in pf.schema.names if c not in ("day", "flow_order")]
    chunks: list[list[np.ndarray]] = [[] for _ in names]
    pos = 0
    for batch in pf.iter_batches(batch_size=50_000, columns=columns):
        frame = batch.to_pandas()
        fingerprints = pd.util.hash_pandas_object(frame, index=False).to_numpy(dtype=np.uint64)
        stop = pos + len(frame)
        cursor = pos
        while cursor < stop:
            owner = int(np.searchsorted(ends, cursor, side="right"))
            boundary = min(stop, int(ends[owner]))
            chunks[owner].append(fingerprints[cursor - pos:boundary - pos])
            cursor = boundary
        pos = stop
    if pos != int(ends[-1]):
        raise ValueError("incomplete parquet scan")
    unique = [np.unique(np.concatenate(parts)) for parts in chunks]
    rows = [
        {"source": CIC_FILES[name], "clean_rows": int(sizes[i]),
         "unique_fingerprints": len(unique[i])}
        for i, name in enumerate(names)
    ]
    pairs = [
        (CIC_FILES[names[i]], CIC_FILES[names[j]],
         int(np.intersect1d(unique[i], unique[j], assume_unique=True).size))
        for i in range(len(names)) for j in range(i + 1, len(names))
    ]
    return rows, pairs


def main() -> None:
    processed = ROOT / "data" / "processed"
    rows, pairs = audit(processed / "cicids2017_clean.parquet",
                        processed / "cleaning_report.csv")
    lines = [
        "# CICIDS2017 cross-file content audit", "",
        ("Generated by `python scripts/audit_cicids_cross_file.py` from the "
         "cleaned parquet and its cleaning report. The cleaner concatenates "
         "the eight CSVs in the order shown below."), "",
        ("| Source CSV | Clean rows | Unique feature+label fingerprints | "
         "Repeated model-input rows within file |"),
        "|---|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(f"| `{row['source']}` | {row['clean_rows']} | "
                     f"{row['unique_fingerprints']} | "
                     f"{row['clean_rows'] - row['unique_fingerprints']} |")
    lines += ["", "| Source A | Source B | Shared unique fingerprints |",
              "|---|---|---:|"]
    for a, b, count in pairs:
        lines.append(f"| `{a}` | `{b}` | {count} |")
    lines += [
        "", ("These are 64-bit pandas hashes of the normalized class label and "
             "retained numeric features, excluding `day` and `flow_order`. Hash "
             "collisions are possible; matches are content-fingerprint candidates, "
             "not proof of identical packets or source-row identity. The cleaner "
             "deduplicated full rows before dropping identifiers and normalizing "
             "labels; this left many repeated model-input rows within and across "
             "source files. The duplicate-disjoint sensitivity arm deduplicates the "
             "pooled feature+label records before task sampling and split."),
    ]
    out = ROOT / "docs" / "cicids_cross_file_audit.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}; {sum(count > 0 for _, _, count in pairs)} nonzero pairs")


if __name__ == "__main__":
    main()
